package com.whatsbotai.domain.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import com.whatsbotai.domain.enums.TenantPlan;
import com.whatsbotai.domain.enums.TenantStatus;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

import java.time.LocalDateTime;

/**
 * Root entity representing a customer business subscribing to WhatsBotAI.
 *
 * <p>A Tenant represents a cellphone repair shop owner who pays for the platform.
 * Every other entity in the system (Conversation, Message, KnowledgeEntry, etc.)
 * belongs to a Tenant via a {@code tenant_id} foreign key, enforcing strict data
 * isolation between customers.
 *
 * <p>The Tenant lifecycle starts in {@link TenantStatus#TRIAL} for 7 days, then
 * transitions to {@link TenantStatus#ACTIVE} upon successful AbacatePay subscription.
 * Each active tenant has a dedicated Baileys microservice instance provisioned on
 * Fly.io, identified by {@code baileysAppName}.
 *
 * @author Kauan Santos Ferreira
 * @version 1.0
 * @since 2026
 * @see TenantStatus
 * @see TenantPlan
 */

@Entity
@Table(name = "tb_tenant")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString
@EqualsAndHashCode(of = "id")
public class Tenant {

    /** Unique identifier of the tenant (auto-generated by the database). */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Business name of the tenant (e.g., "Tech Repair Shop"). */
    @Column(name = "name", nullable = false, length = 150)
    private String name;

    /** Owner's email address; used for login and unique across all tenants. */
    @Column(name = "owner_email", nullable = false, unique = true, length = 255)
    private String ownerEmail;

    /** Brazilian tax identifier (CNPJ) of the business; optional but unique when set. */
    @Column(name = "tax_id", unique = true, length = 20)
    private String taxId;

    /** Contact phone number of the tenant owner. */
    @Column(name = "phone", length = 20)
    private String phone;

    /** Current lifecycle status; controls bot access and data retention policy. */
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = 30)
    private TenantStatus status;

    /** Current subscription plan; controls feature access and quotas. */
    @Enumerated(EnumType.STRING)
    @Column(name = "plan", nullable = false, length = 30)
    private TenantPlan plan;

    /** Fly.io app name of the dedicated Baileys instance for this tenant. */
    @Column(name = "baileys_app_name", length = 100)
    private String baileysAppName;

    /** Timestamp when the trial period ends (null for non-trial tenants). */
    @Column(name = "trial_ends_at")
    private LocalDateTime trialEndsAt;

    /** AbacatePay subscription identifier for billing reference. */
    @Column(name = "subscription_id", length = 100)
    private String subscriptionId;

    /** Timestamp when the tenant record was created (managed by Hibernate). */
    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update to this tenant record (managed by Hibernate). */
    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

}
